### ISSUE TITLE
WARP without Docer

### ISSUE THREAD

**Issue by DzeTro** [sebo-b/warp#23]
Hello Sebo-b

thanks for your previous answer.

Is there a way to install and use WARP without Docker?

**Comment by sebo-b** [comment]
yes - it is described in [without Docker - the old way](https://github.com/sebo-b/warp#without-docker---the-old-way) section of the readme.

If you want to use it on production, instead of using Flask built-in HTTP server, you should use uWSGI or gunicorn with rev-proxy or Apache with mod_wsgi.

btw: why do you want to use it without Docker?

**Comment by DzeTro** [comment]
I should test WARP on our server to see if we could use it. Unfortunately, I lack the 
necessary permissions, and they don't want to have Docker. I don't understand this either, as Docker works very well on my PC.

Now we go the old way via the command inputs 

    Am Montag, 3. April 2023 um 21:51:38 MESZ hat sebo-b ***@***.***> Folgendes geschrieben:  
 
 


yes - it is described in without Docker - the old way section of the readme.

If you want to use it on production, instead of using Flask built-in HTTP server, you should use uWSGI or gunicorn with rev-proxy or Apache with mod_wsgi.

btw: why do you want to use it without Docker?
